name: test

on:
  pull_request:
    types: [opened, edited]
  release:
    types: [created]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Test
        run: go test -coverprofile=coverage.out ./..
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
