name: test

on:
  pull_request:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
 
    - name: Test
      run: go test -coverprofile=coverage.xml ./... && go tool cover -func=coverage.xml

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
